[project]
authors = [{ name = "asmith" }, { email = "alastair.smith@ndcls.ox.ac.uk" }]
name = "capcruncher-tools"
version = "0.2.4"
description = "Extra utilities to enhance CapCruncher"
readme = "README.md"
requires-python = ">=3.12"
license = { file = "LICENSE" }
dependencies = [
    "click>=8.0.0,<9.0.0",
    "loguru>=0.7.0,<0.8.0",
    "pandas>=2.1.0,<3.0.0",
    "polars>=1.6.0,<2.0.0",
    "pyranges1>=1.3.0,<2.0.0",
    "ray>=2.8.0,<3.0.0",
    "tabulate>=0.9.0,<1.0.0",
    "tqdm>=4.65.0,<5.0.0",
]


[build-system]
build-backend = "maturin"
requires = ["maturin==1.13.1"]

[tool.maturin]
features = ["pyo3/extension-module"]
python-source = "python"
profile = "release"
compatibility = "linux"

[package.metadata.maturin]
name = "capcruncher_tools.capcruncher_tools_rs"


[project.scripts]
capcruncher-tools = "capcruncher_tools.cli:cli"

[dependency-groups]
dev = [
    "maturin==1.13.1",
    "pytest==9.0.3",
    "ruff==0.15.11",
]


[project.urls]
repository = "https://github.com/alsmith151/CapCruncherTools"
